##
# indicates the current PWM levels of the thrusters.
# thrusters 0 -> 3 are the horizontal ones, starting to count from the upper-left thruster ( seeing the ROV from the TOP, watching towards the direction of the front camera ), 
# proceeding to count clock-wise.
# thrusters 4 -> 7 are the vertial ones, starting to count from the upper-left thruster ( seeing the ROV from the TOP, watching towards the direction of the front camera ), 
# proceeding to count clock-wise.
int16 thruster0
int16 thruster1
int16 thruster2
int16 thruster3
int16 thruster4
int16 thruster5
int16 thruster6
int16 thruster7